// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ServicecesTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ServicecesTest', async function() {
    await driver.get("http://localhost:3000/")
    {
      const element = await driver.findElement(By.css(".MuiIconButton-edgeStart > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiIconButton-edgeStart > .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css("a:nth-child(2) .MuiTypography-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("a:nth-child(2) .MuiTypography-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiIconButton-sizeLarge > .MuiSvgIcon-root")).click()
    await driver.findElement(By.id("Path")).click()
    await driver.findElement(By.id("Path")).click()
    await driver.findElement(By.id("Path")).sendKeys("node")
    await driver.findElement(By.css(".MuiButton-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiFab-sizeLarge path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiFab-sizeLarge path")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiFab-sizeLarge > .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiFab-sizeSmall:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiFab-sizeSmall:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("Path")).sendKeys("node")
    await driver.findElement(By.css(".MuiButton-root")).click()
    await driver.findElement(By.css(".MuiButton-text")).click()
    await driver.findElement(By.css(".MuiBackdrop-root")).click()
    await driver.findElement(By.css(".css-78trlr-MuiButtonBase-root-MuiIconButton-root > .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiSvgIcon-fontSizeLarge > path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiSvgIcon-fontSizeLarge > path")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("enhanced-table-checkbox-1")).click()
    {
      const element = await driver.findElement(By.css(".css-78trlr-MuiButtonBase-root-MuiIconButton-root:nth-child(2) path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".css-78trlr-MuiButtonBase-root-MuiIconButton-root:nth-child(2) path")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-text"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-text")).click()
    {
      const element = await driver.findElement(By.css(".css-9sors8-MuiButtonBase-root-MuiIconButton-root > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".css-9sors8-MuiButtonBase-root-MuiIconButton-root > .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiFab-sizeLarge > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiFab-sizeLarge > .MuiSvgIcon-root")).click()
    await driver.findElement(By.css(".MuiFab-sizeLarge > .MuiSvgIcon-root")).click()
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(2)")).click()
    await driver.findElement(By.css(".MuiButton-text")).click()
  })
})
