// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Shared_Functionalities', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Shared_Functionalities', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.css(".MuiIconButton-edgeStart path")).click()
    await driver.findElement(By.css("a:nth-child(1) .MuiTypography-root")).click()
    await driver.findElement(By.css(".css-1k455el > .MuiButtonBase-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiOutlinedInput-root > #tenant"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiBackdrop-root"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css(".MuiMenuItem-root:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.css(".MuiOutlinedInput-root > #tenant"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiBackdrop-root"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css(".MuiMenuItem-root:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.css(".MuiIconButton-sizeSmall path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiIconButton-sizeSmall path")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiMenuItem-root:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.id("language-select"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiBackdrop-invisible"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css(".MuiMenuItem-root:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.id("language-select"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiBackdrop-invisible"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css(".MuiMenuItem-root:nth-child(3)")).click()
    {
      const element = await driver.findElement(By.id("language-select"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiBackdrop-invisible"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css(".MuiMenuItem-root:nth-child(2)")).click()
    await driver.findElement(By.css(".css-9sors8-MuiButtonBase-root-MuiIconButton-root path")).click()
    {
      const element = await driver.findElement(By.id("demo-customized-button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("demo-customized-button")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiMenuItem-root:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.id("demo-customized-button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("demo-customized-button")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiMenuItem-root:nth-child(1)")).click()
  })
})
