// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TenanTests', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TenanTests', async function() {
    await driver.get("http://localhost:3000/")
    {
      const element = await driver.findElement(By.css(".MuiIconButton-edgeStart > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiIconButton-edgeStart > .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css("a:nth-child(1) .MuiTypography-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("a:nth-child(1) .MuiTypography-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiGrid-root:nth-child(2) .MuiSpeedDial-root > .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".css-1e2cad8-MuiButtonBase-root-MuiFab-root-MuiSpeedDialAction-fab:nth-child(1)")).click()
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css("#icons path")).click()
    await driver.findElement(By.css(".MuiMenuItem-root:nth-child(5) path")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(4) .placeholder:nth-child(2)")).click()
    await driver.findElement(By.id("outlined-basic")).click()
    await driver.findElement(By.id("outlined-basic")).sendKeys("rgb(128, 134, 199)")
    await driver.findElement(By.id("outlined-basic")).sendKeys(Key.ENTER)
    {
      const element = await driver.findElement(By.css(".MuiGrid-root:nth-child(5) .react-colorful__hue > .react-colorful__interactive"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiGrid-root:nth-child(5) .react-colorful__hue .react-colorful__pointer"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".MuiDialogContent-root")).click()
    await driver.findElement(By.css(".MuiButton-text")).click()
    {
      const element = await driver.findElement(By.css(".MuiGrid-root:nth-child(2) .MuiCardActions-root > div path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiGrid-root:nth-child(2) .MuiCardActions-root > div path")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorSecondary > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiIconButton-colorSecondary > .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-text"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("Path")).click()
    await driver.findElement(By.id("Path")).sendKeys("node")
    {
      const element = await driver.findElement(By.css(".MuiButton-text"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-text")).click()
    await driver.findElement(By.id("enhanced-table-checkbox-1")).click()
    {
      const element = await driver.findElement(By.css(".css-78trlr-MuiButtonBase-root-MuiIconButton-root:nth-child(2) > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".css-78trlr-MuiButtonBase-root-MuiIconButton-root:nth-child(2) > .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-text"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-text")).click()
    {
      const element = await driver.findElement(By.css(".css-9sors8-MuiButtonBase-root-MuiIconButton-root > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".css-9sors8-MuiButtonBase-root-MuiIconButton-root > .MuiSvgIcon-root")).click()
  })
})
