version: "3.7"
services:
  policy-api:
    image: orchestracities/anubis-management-api:master
    networks:
      - envoymesh
    environment:
      - CORS_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_METHODS=*
      - CORS_ALLOWED_HEADERS=*
      - DEFAULT_POLICIES_CONFIG_FILE=/home/apiuser/config/opa-service/default_policies.ttl
      - DEFAULT_WAC_CONFIG_FILE=/home/apiuser/config/opa-service/default_wac_config.yml
      - DB_TYPE=sqlite
    volumes:
      - ./opa-service/default_policies.ttl:/home/apiuser/config/opa-service/default_policies.ttl
      - ./opa-service/default_wac_config.yml:/home/apiuser/config/opa-service/default_wac_config.yml
    ports:
      - "8085:8000"

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - envoymesh

  keycloak:
    image: jboss/keycloak:${KEYCLOAK_VERSION:-16.1.1}
    # if your platform is linux/arm64 use the following image
    # image: koolwithk/keycloak-arm:16.0.0
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/oc-custom.jar:/opt/jboss/keycloak/standalone/deployments/oc-custom.jar
      - ./keycloak/realm-export.json:/opt/jboss/realm-export.json
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - JAVA_TOOL_OPTIONS=-Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/jboss/realm-export.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    networks:
      - envoymesh

  management-ui:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: orchestracities/management-ui
    ports:
      - "3000:3000"
    networks:
      - envoymesh

  configuration-api:
    build:
      context: ./configuration-api
      dockerfile: ./Dockerfile
    env_file: .env
    image: orchestracities/configuration-api
    ports:
      - "4000:4000"
    networks:
      - envoymesh

volumes:
  mongodata:

networks:
  envoymesh: {}
