version: "3.7"
services:
  policy-api:
    image: orchestracities/anubis-management-api:master
    networks:
      - envoymesh
    environment:
      - CORS_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_METHODS=*
      - CORS_ALLOWED_HEADERS=*
      - DEFAULT_POLICIES_CONFIG_FILE=/home/apiuser/config/opa-service/default_policies.ttl
      - DEFAULT_WAC_CONFIG_FILE=/home/apiuser/config/opa-service/default_wac_config.yml
      - DB_TYPE=sqlite
    volumes:
      - ./opa-service/default_policies.ttl:/home/apiuser/config/opa-service/default_policies.ttl
      - ./opa-service/default_wac_config.yml:/home/apiuser/config/opa-service/default_wac_config.yml
    ports:
      - "8085:8000"

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - envoymesh

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-19.0.1}
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/oc-custom.jar:/opt/keycloak/providers/oc-custom.jar
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts 
    command: start-dev --import-realm
    networks:
      - envoymesh

volumes:
  mongodata:

networks:
  envoymesh: {}
