version: "3.7"
services:
  policy-api:
    image: orchestracities/anubis-management-api:master
    networks:
      - envoymesh
    environment:
      - CORS_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_METHODS=*
      - CORS_ALLOWED_HEADERS=*
      - DEFAULT_POLICIES_CONFIG_FILE=/home/apiuser/config/opa-service/default_policies.ttl
      - DEFAULT_WAC_CONFIG_FILE=/home/apiuser/config/opa-service/default_wac_config.yml
      - DB_TYPE=sqlite
      - KEYCLOACK_ENABLED=True
      - TENANT_ADMIN_ROLE_ID=9dc79aa8-d42f-4720-8de0-fe79a00a46b7
      - KEYCLOACK_ADMIN_ENDPOINT=http://keycloak:8080/admin/realms/default
    volumes:
      - ./opa-service/default_policies.ttl:/home/apiuser/config/opa-service/default_policies.ttl
      - ./opa-service/default_wac_config.yml:/home/apiuser/config/opa-service/default_wac_config.yml
    ports:
      - "8085:8000"

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - envoymesh

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-19.0.1}
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/oc-custom.jar:/opt/keycloak/providers/oc-custom.jar
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts 
    command: start-dev --import-realm
    networks:
      - envoymesh
    
  upstream-service:
    image: fiware/orion:${ORION_VERSION:-3.3.1}
    ports:
      - "1026:1026"
    command: -logLevel DEBUG -noCache -dbhost mongo -corsOrigin __ALL
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:1026/version"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - envoymesh

volumes:
  mongodata:

networks:
  envoymesh: {}
