name: Graphql-tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: 'Node.js v${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 14
    steps:
       - name: Generate env file
        run: cp .env.docker .env
      - name: Set up Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - name: Install Node.js dependencies Management UI
        run: npm ci
        working-directory: configuration-api
      - name: Run All Node.js Tests
        run: npm run test
        working-directory: configuration-api