name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  # Replace pull_request with pull_request_target if you
  # plan to use this action with forks, see the Limitations section
  pull_request:

jobs:
  javascript:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci
      - name: ESLint Management UI
        run: npx --no-install eslint src/ --cache --fix
      - name: ESLint Configuration API
        run: |
          cd graphql-server
          npx --no-install eslint main/ --cache --fix
          cd ..
      - name: ESLint Documentation
        run: |
          cd documentation
          npx --no-install eslint . --ext .js,.jsx --cache --fix 
